namespace Uniqua.Projector.Domain;

/// <summary>
/// The one source of new entity identifiers. Ids are generated by the application, never by the
/// database, and they are GUID version 7 — time-ordered, so inserts stay at the end of the
/// clustered index instead of fragmenting it, and sequential enough to sort by without leaking
/// how many rows exist (see docs/architecture-map.md § Conventions).
/// </summary>
public static class Ids
{
    public static Guid New() => Guid.CreateVersion7();

    public static Guid New(DateTimeOffset timestamp) => Guid.CreateVersion7(timestamp);
}
